// import { TimeSharingData } from "../views/stockPage/StockChart"
//
// // ChartData.ets - 数据结构和模拟数据
// export interface TimeSharingData {
//   time: string
//   price: number
//   volume: number
// }

// export interface KLineData {
//   date: string
//   open: number
//   close: number
//   high: number
//   low: number
//   volume: number
// }
//
// // 模拟数据生成
// export function generateTimeSharingData(): TimeSharingData[] {
//   return TimeSharingData[]=[]
//   // 生成分时数据逻辑
// }
//
// export function generateKLineData(): KLineData[] {
//   return
//   // 生成K线数据逻辑
// }